# OSSTIDBURN ?? {-}

<h2><span>WHAT’S THAT?</span></h2> 

OsstidBurn is a regional Burn, which is a participative art event organized by local Burners to bring Burning Man culture and principles to their local communities.The website for the event is the following: https://losstidburn.org/


See https://regionals.burningman.org for a list of all official regional burns.

L’OsstidBurn has been recognized by Burning Man as an official regional event since its inception in 2016.

<h2><span>MISSION?</span></h2>

OsstidBurn’s mission is to promote engagement in art and participation. Inspired by the 10 principles of Burning Man, L’OsstidBurn encourages participants to express their creativity freely and radically.

The eclectic OsstidBurn community is made up of people from all walks of life: artists, scientists, engineers, shamans, nurses, chefs, plumbers, philosophers, accountants, etc. Everyone converges to co-create a temporary zone  of self-expression. Participants paint, weld, sculpt, burn things, write code, cook with a lot of oil and sometimes practice biodanza... In short, they create remarkable interactive experiences.

<h2><span> OSSTIDBURN 2025 </span></h2>

**THEME 2025: AAAAAAAAAHHHHHHH !!**


It's this precise emotion that we've all been feeling, each in our own way, since the beginning of 2025. AAAAAAAAAAAAAAAAHHHHHHHHHHHHH is the primal scream that motivates and unites us, like a banner flying in the wind.

**WHEN?**


June 19 (Thursday) – 24 (Tuesday), 2025


**WHERE?**

The address and directions will be sent to all ticket holders 48 hours before the event.

Eastern Townships

* 1 hour 40 minutes from Montreal
* 3 hours from Quebec City

<h2><span>WHERE DOES THE NAME OSSTIDBURN COME FROM?</span></h2> 

The name of the event is a reference to Osstidcho, an anti-conformist and revolutionary show presented for the first time on June 20, 1968 at Théâtre du Quat’Sous in Montreal.  The concept was simple: change the customs of theater by  combining different disciplines. In the end, the owner of the Quat’Sous Theatre got fed up with the chaos and unruliness of the members of the young troupe, for whom art came from disorder. Osstidcho is a show that will leave an indelible mark on Quebec’s collective imagination.

<h2><span>WHAT IS THIS PLACE?</span></h2>

<h3><span>A LAND WITH MANY ORIGINS</span></h3> 

Although we have good knowledge of the recent and colonial history of the event site, we are conscious of the fact that its history is much more complex and meaningful than only that. The Organization is currently working to create a land acknowledgement to recognize the local Indigenous communities. The project is still in its early stages. If you would like to help with this project, please contact info@losstidburn.org

<h3><span>ON BULL’S LAND…</span></h3> 


Gerald V. Bull, born on March 9, 1928 in Ontario, and assassinated on March 22, 1990 in Brussels, was a Canadian engineer specialized in ballistics (the science that studies the movement of projectiles). He conducted extensive research on superguns that could fire over very long distances or high altitudes. In 1971, Gerald Bull founded a ballistics research company—the Space Research Corporation (SRC)—in Highwater near Mansonville in the Eastern Townships, to continue his research. 

It was a golden era for the Eastern Townships. Locals were fascinated by the work of Gerald Bull’s company. It is said that people heard the cannons firing all the way to Sutton and that neighbours regularly had to replace their windows that broke during tests. They nicknamed him Dr. Strangelove.

The Canadian government dismantled all the remaining cannons on the property, but some vestiges remain, such as an old antenna, power station, manhole and the foundations of several buildings.

