# BON VOISINAGE {-}

Nous avons de nouveaux voisins. Eh oui, le développement immobilier a aussi touché le Canton de Potton. Maintenir une bonne relation avec eux est névralgique pour la pérennité de l’événement sur ce site que nous nous sommes appropriés. 

**C’est pourquoi on demande ta collaboration pour le bon respect du voisinage.**

* Aucune musique, système de son, événements et les rassemblements dont des partys seront tolérés sur la plaine et stationnement.
* Conduisez lentement et de façon civilisée dans le Canton de Potton. Afin de réduire les nuisances sonores liées à la circulation des voitures, arrivez pendant les heures d'ouverture de la Gate, respectez la limite de vitesse et évitez la nuisance sonore (ex. techno à plein volume).
* Respecte les panneaux de signalisation qui délimitent le site, sinon, on va te demander de déplacer ta tente. On est entouré de propriété privée.
* Soutenez les commerces locaux ! Dépensez votre argent avec le sourire :) Au village, vous trouverez une excellente boulangerie, un torréfacteur de café et un dépanneur-quincaillerie.
* **STATIONNEMENT INTERDIT SUR LA ROUTE**. Vous devez avoir une pass de parking pour rentrer dans le site. Sinon venez en ride ou avec l'OsstdidBus.
* Ne laissez aucune trace : **NE jetez PAS vos déchets dans les conteneurs du village** — rapportez-les chez vous.

