# ARRIVÉES {-}

Le site est en pleine forêt : pour votre sécurité, il est fortement conseillé d’arriver de jour, à la clarté. 
Vous allez devoir nettoyer votre espace de campement de branches, roches, feuilles. Apportez des gants de travail et des outils pour aménager votre espace. 

<h2><span> Horaires </span></h2> 

"EARLY ARRIVALS" 

* 19 Juin - Jeudi: 09h00 à 24h00 

ACCÈS GÉNÉRAL 

* 20 Juin - Vendredi: 09h00 à 24h00 
* 21 Juin - Samedi: 09h00 à 24h00  
* 22 Juin - Dimanche: 09h00 à 17h00 

EXODUS 

* 24 Juin - Mardi: 09h00 à 14h00 

LAISSE PAS D’TRACE (MOOP SWEEP)

* 24 Juin - Mardi: 14h00 à 18h30


<h2><span> Autres infos </span></h2> 


ACCÈS AU SENTIER PAR VÉHICULE 4X4


* Jeudi: 05h00 à 20h30
* Vendredi: 05h00 à 20h30 
* **Samedi à lundi : aucun véhicule autorisé sur le sentier**
* Mardi: 05h00 à 14h00 

Voir prochaine section (billets) pour plus de détails


PERIODES DE SILENCE (sans musique amplifiée ni génératrices) 

* Jeudi à lundi :  6h00 à 12h00 
* Mardi : de 6h au début de l'Exodus. 

Cette politique est sujette à changement au courant de l’événement, voir section "Camping et autres infos".
