# TICKETS & ACCESS {-}

No ticket, no entry!

Make sure you have your ticket AND that each person in your vehicle has theirs

* You must present your ticket (PDF or digital) and photo ID that matches the name and date of birth listed on your ticket.
* If your chosen name differs from your legal name, let the volunteers at the gate know—feel free to add a post-it with your chosen name to your ID.
* Participants under 18 will receive a distinctive wristband and will not have access to alcohol service.



<h2><span>ENTRY PROHIBITED</span></h2> 

Anyone attempting to enter without a ticket will be immediately expelled and banned from future OsstidBurn events.

* Smuggling people in or helping someone bypass the gate **is just as serious** as doing it yourself.
* **The entire vehicle** will be turned away with **no refund**.
* Respect the rules, respect the volunteers.


Be kind to the organizers—they’re volunteers too, just like you.

<h2><span>CARBON-NEUTRAL ACCESS TO THE SITE</span></h2> 

**Looking for a carpool spot?** It's good for the environment and helps reduce the number of cars on-site. Here’s the [link for OsstidBurn 2025’s](https://www.groupcarpool.com/t/25kbzo) carpooling platform to organize one.

**What if I can’t find a carpool?** Well, think about the OsstidBus! The OsstidBus is a carbon-neutral collective transport project, led since 2022 by members of the Org, which we adapt every year to make it as accessible as possible. To get your OsstidBus ticket: https://losstidburn.org/en/transportation/


<h2><span> VEHICLE ACCESS </span></h2> 

Access to the site is via a bumpy road. The last stretch before the entrance and parking area is rough—please drive very slowly.

Only 4x4 vehicles with a minimum clearance of 12 inches (30 cm) can access the campsite trails. 4x4 vehicles equipped with mud tires may be allowed if conditions permit.

All vehicles must be approved by the **ASS (Access Support Squad)**, which has the final say depending on trail conditions.

If the trail is deemed unusable by the landowner or DPW (e.g., due to mud), a shuttle system using ATVs will be set up to tow trailers.


ACCESS TO THE TRAIL BY 4X4 VEHICLE


Thursday: 5:00 AM to 8:30 PM (**Early Arrivals only**)\
Friday: 5:00 AM to 8:30 PM vehicles \
Saturday: No vehicles \
Sunday: No vehicles \
Monday: No vehicles \
Tuesday: 5:00 AM to 2:00 PM \

<h2><span> DON’T HAVE A 4X4? </span></h2> 

Upon your arrival at OsstidBurn, you will need to leave your vehicle in the parking area and carry your gear in by foot. The trails are not suitable for any standard road vehicle.
 
Be prepared! It’s about 800 meters (a 15-minute walk) from the parking lot to the camping area. 

We recommend bringing a dolly, cart, ropes, or any gear that can help you haul your stuff.

The OsstidBurn site has limited space for parking. The Parking Team works magic every year to fit everyone in—follow their guidance!

If you're coming by car, you **MUST** have a parking pass for your car or RV (recrational vehicle). Every vehicle must have its own pass.

Get your parking pass here: https://participation.losstidburn.org/


