# BURN BARREL {-}

<h2><span>RÈGLES ET MODALITÉS D’USAGE</span></h2> 

Veuillez ne pas creuser ou démarrer votre propre feu de camp. Utilisez plutôt les «burn barrels» désignés (ou autre instrument de feu autorisé), et partagez-en la chaleur et la compagnie. Ne brûlez que du bois mort provenant de la forêt, des feuilles mortes ou des brindilles dans les «burn barrel». Il est strictement interdit de couper du bois dans la forêt. Ne brûlez pas de plastique, de bois traité ou peint ou autres items. 

Un «burn barrel» (ou autre instrument de feu autorisé) est un dispositif permettant d’allumer un  feu et d’en répandre la chaleur en toute sécurité, tout en évitant d’être un élément de propagation de feu. Afin d’être conforme aux exigences de L’OsstidBurn, il doit répondre à des critères précis, soit être sur pattes et avoir un dégagement de 15 centimètres (6 pouces) du sol et être couvert par un grillage avec des trous d’au plus ½ pouce (1cm) afin d’éviter l’envol de tisons. De plus, pour opérer un «burn barrel» ou  un autre instrument de feu autorisé, il faut balayer le sol de toutes les feuilles et les brindilles dans un périmètre autour de l’instrument  équivalent à sa hauteur. Ainsi, un «burn barrel»  haut de 1 mètre (3 pieds) devrait avoir un périmètre dégagé autour de lui de 1 mètre (3 pieds).  


Chaque camp peut apporter et prendre en charge  son «burn barrel». Pour ce faire, il faut  d’abord en faire la demande officielle au comité FAST en remplissant ce formulaire:  
https://forms.gle/iis4tdhxtQzHv74X6 


Lors de l’événement, AVANT L’ALLUMAGE, tout dispositif de feu devra être vérifié et autorisé sur les lieux par un membre de FAST. 
Les brûleurs de camping sont permis pour cuisiner, mais aucun feu au sol ne sera autorisé. Dans ce cas, assurez-vous d’avoir un extincteur en lieu visible près de votre espace de cuisine. 


Les appareils au gaz sans modifications approuvés par une organisation reconnue par la RBQ sont permis. (e.g. chaufferettes radiantes). 

Pour de tels appareils: 

* Un·e opérateur·trice sobre doit en tout temps être présent·e lorsque l’appareil est en fonction. 
* Positionnez l’appareil dans un espace dégagé et assurez-vous de la stabilité de l’appareil  lorsque déployé. 
* Nettoyez toutes feuilles et brindilles dans un espace de 1.5 mètres autour de l’appareil et assurez-vous que l’espace soit suffisamment dégagé en haut de l’appareil. 
* Feux de camp & risque de feu de forêt 
* Assurez-vous que tout autre combustible  (propane, essence, etc.) soit à plus de 10  mètres de l’appareil en fonction. 
* Gardez en tout temps un extincteur d’incendie en lieu visible et à moins de 5 mètres de l’appareil. 


Aucun effet pyrotechnique ou feu d’artifice ne sera autorisé.  
Les torches portables à l’huile (torches tiki) et  tout autre type de torche ou chandelle à flamme ouverte ne sont pas permises à l’événement.
