# BURNING MAN :: 10 principes {-} 

**Ces principes ne sont ni des commandements, ni des règlements. Ils suggèrent une ligne de conduite qui permet une organisation communautaire distincte**
**Une participation à un tel événement pourrait changer votre perception du monde qui vous entoure et éventuellement influencer votre façon d'interagir avec celui-ci.**


<h2><span> RESPONSABILITÉ CIVILE  </span></h2>
Chacun·e se doit d’avoir un comportement civique et respectueux des autres, et de respecter les 10 principes qui régissent l’événement. 
Les membres de la communauté qui organisent des événements doivent assumer la responsabilité du bien-être public et s’efforcer de communiquer les responsabilités civiques aux participant·e·s. Iels doivent également assumer la responsabilité de mener les événements conformément aux lois locales, nationales et fédérales. 


<h2><span> PARTICIPATION </span></h2>
L’OsstidBurn repose sur la participation de tout le monde. C’est pourquoi chaque personne est encouragée à être plus qu’une simple spectatrice et à participer à l'événement dans tous les sens du terme, soit en y prenant part et en en faisant partie. Le succès de l’événement dépend de votre implication. C’est vous qui faites ce que l’événement est!  
 
<h2><span> EFFORT COMMUNAUTAIRE </span></h2>
La collaboration, la coopération, l’entraide et  les actes collectifs sont essentiels dans le projet BM. Ceci s’applique à son camp, ainsi qu’à l’événement qui est en constante recherche de volontaires pour des tâches de toutes sortes. Il est donc important de s’impliquer et de donner du temps de volontariat durant l’événement. N'oubliez pas de vous inscrire sur la plateforme afin de combler au moins deux postes de volontariat durant l’événement. 
https://participation.losstidburn.org

<h2><span> IMMÉDIATETÉ </span></h2>
Nous faisons partie d’une belle expérience. Chacun·e a le droit de se reconnaître dans l'expression de ce qu’iel aime ou de ce qu’iel veut apprendre à connaître, chacun·e s’exprime immédiatement dans le thème qu’iel désire, tout le monde participe en société à la création d’un projet qui prône le développement humain et artistique.  

<h2><span> AUTONOMIE RADICALE </span></h2>
Chaque personne est encouragée à se découvrir et à utiliser ses ressources intérieures. Chaque personne se prend donc en charge à L’OsstidBurn tout en faisant attention aux autres. 

<h2><span> LAISSE PAS D’TRACE (LNT) </span></h2>
L’OsstidBurn est un événement "Laisse pas  d’trace". Tout ce qui n’est pas à l’origine sur  le site doit être rapporté avec soi. Vous devez donc ramener tous vos effets personnels ainsi que vos déchets après l’événement. Il n’y aura pas de conteneur à vidange à la sortie de l’événement. Il est important de prévoir d’apporter des sacs poubelle et du matériel pour gérer tous vos déchets, incluant le recyclage et le compost. 
De plus, la propreté du site est une responsabilité commune et l’entretien du site est l’affaire  de tous·tes. Pensez à avoir avec vous en tout temps un petit sac pour ramasser les déchets que vous apercevez sur le sol, même s’ils ne viennent pas de vous. Il est aussi fortement suggéré de participer à la corvée de nettoyage (MOOP SWEEP) globale à la fin de l’événement, en plus de celle que vous aurez effectuée sur votre campement. Consultez le guide du LNT pour de plus amples informations. 

<h2><span> EXPRESSION DE SOI RADICALE  </span></h2>
L’ouverture d’esprit est un principe fondamental. Laissez-vous transporter par votre fibre artistique et votre goût prononcé pour la fête. Exprimez-vous librement, personne ne vous jugera.  



<h2><span> DON </span></h2>
Le don est très important à L’OsstidBurn, sans attente de retour. Le don n’est pas forcément  matériel: il peut prendre la forme d’un service, d’un poème, ou d’un soin apporté à l’autre.  

<h2><span> DÉCOMMODIFICATION </span></h2>
L’OsstidBurn exclut toute forme de commerce, de publicité, de commandite ou d’activités commerciales. L’argent ne sert donc à rien sur place. Nous encourageons la participation et l'expérience individuelle à la consommation pure. 


<h2><span> INCLUSION RADICALE </span></h2>
L’Osstidburn accepte tout le monde. Chaque personne est une partie intégrante de l’événement. Chacun·e s’inclut et inclut les autres, quelque soit leur origine, religion ou préférence sexuelle. So «Include yourself, include others!»


<h2><span> CONSENTEMENT: PRINCIPE 0 </span></h2>  
L’OsstidBurn est un environnement extrêmement libre et ouvert d’esprit. Nous souhaitons créer un espace suffisamment sécurisé (safe-enough) pour tous·tes. Comme pour les autres principes, le bien-être et la sécurité de chacun·e est garanti par une intention collective de respecter et d’appliquer un principe de consentement avant toute interaction.
