# CONSENTEMENT {-}

1.  <span style="text-decoration:underline">Le consentement concerne tous types d’interactions à deux ou à plusieurs </span>(câlins, discussions, toucher, danse, sexe, s’asseoir à côté de quelqu’un...) 


2. <span style="text-decoration:underline">Unanime, explicite et renouvelable </span>
  
  
* Toute interaction (physique ou autre) nécessite le consentement <span style="text-decoration:underline"> EXPLICITE de toutes les  personnes impliquées </span> dans l’échange.  
* <span style="text-decoration:underline">  Le consentement devrait toujours être VERBAL, PRÉALABLE et RENOUVELABLE. </span> 
* Le consentement peut être retiré à tout moment : n’importe quelle interaction peut être  arrêtée à n’importe quel moment par les personnes impliquées, sans justification. 


3. <span style="text-decoration:underline"> À la recherche du OUI enthousiaste </span> 
  
* Chaque personne est invitée à trouver et rester dans un OUI authentique et enthousiaste,  avant et pendant l’interaction. 
* Si vous n’êtes pas 100% certain·e de vouloir cette interaction, il est peut-être préférable de rester dans un NON.
* Un NON est une réponse complète et ne demande aucune justification/explication. Si  toutes les personnes le souhaitent, il est possible de négocier pour trouver un OUI ENTHOUSIASTE. 


4.<span style="text-decoration:underline">  La nudité, l’habillement, le costume ou le comportement d’une personne NE CONSTITUENT PAS une invitation à une quelconque interaction. </span> 
  
  
5. <span style="text-decoration:underline">  Le consentement doit être LIBRE et CONSCIENT. </span> 
Une personne endormie ou sous la contrainte n’est pas consentante. La prise de substance(s)  (alcool, drogues, cannabis…) ou même l’énergie sexuelle et l’intimité physique peuvent également altérer la conscience. Il est donc nécessaire d’être d’autant plus vigilant·e·s si vous  consommez ou êtes en interaction avec une/des personnes dans un état altéré de conscience.  

Toutes les personnes impliquées comprennent à quoi elles s’engagent en acceptant l'interaction: <span style="text-decoration:underline"> le consentement doit être éclairé. </span> 


6. <span style="text-decoration:underline"> Responsabilité collective </span> 
Comme les autres principes, le consentement est la responsabilité de tous·tes. La communauté de L’OsstidBurn s’engage à intégrer ces principes avec bienveillance, et à prendre soin de les faire respecter pour soi et les autres, en tant qu’acteur·trice et témoin. Chacun·e est responsable de valider et vérifier le consentement de ses partenaires, de nommer clairement ses OUI et ses NON, et de respecter les limites exprimées à chaque instant.  


L’adhésion à ces principes assure un espace plus sécuritaire pour tous·te·s à nommer et faire respecter leur NON. 


**QUE FAIRE SI VOUS ÊTES VICTIME OU TÉMOIN D’UNE VIOLATION DE CONSENTEMENT?**

* Si un·e participant·e semble mettre mal à l’aise les personnes avec qui iel interagit ou dépasse les limites explicitement consenties, n’hésitez pas à l’exprimer ouvertement. 
* Si vous ne vous sentez pas à l’aise d’agir, approchez les Rangers.  
* Si vous vous sentez vous-même en danger, quittez  la situation immédiatement, et allez trouver les Rangers. 
* Nous vous invitons à informer les Rangers de tout comportement déplacé. 
* L’organisation se réserve le droit d’exclure toute personne au comportement inapproprié. 
* Suite à l’événement, si vous souhaitez nous faire part d’une situation de bris de consentement, n’hésitez pas à contacter le comité Conduite à <span style="text-decoration:underline">conduite@losstidburn.org </span>


<h2><span> COMITÉ CONDUITE  </span></h2>


Le Comité Conduite n’est pas un nouveau comité, mais l’évolution naturelle du Comité Consentement. Ce changement de nom reflète mieux l’élargissement de notre mission, en phase avec les besoins d’une communauté en pleine croissance, et permet de clarifier notre rôle.

Notre mandat principal reste centré sur le consentement : sensibilisation, gestion des plaintes, mise en place de mesures appropriées, ainsi que l’accompagnement des camps qui en font la demande.

Notre champ d’action s’élargit. Le Comité Conduite est également là pour soutenir la communauté face à des situations telles que l’intimidation, le harcèlement, la discrimination, l’abus de pouvoir ou le dossage.

Nous sommes disponibles pour appuyer les comités, les camps ou les participant·e·s qui rencontrent des difficultés interpersonnelles ou organisationnelles.
Notre rôle est préventif autant que réactif : être présent·e·s avant que les situations ne dégénèrent, pour favoriser un environnement de burn sain, respectueux et sécuritaire pour tou·te·s.

Pour joindre le Comité Conduite, vous pouvez écrire à conduite@losstidburn.org. Ce courriel est reçu par Camille C., Elizabeth V., Antonia S., Cléo G. et Meddy B..
Si l’une de ces personnes est impliquée dans la situation ou si, pour toute autre raison, vous préférez qu’elle ne voie pas votre message, vous pouvez contacter directement au moins deux personnes du comité à leur adresse individuelle :

* camille@losstidburn.org
* cleo@losstidburn.org
* elizabeth@losstidburn.org
* antonia@losstidburn.org

À noter : l’adresse consentement@losstidburn.org reste active pour le moment. Elle est accessible uniquement par Elizabeth V. et Antonia S., afin d'assurer la continuité de traitement des messages envoyés à l’ancien comité.

<h2><span> PHOTOGRAPHIE  </span></h2>

Photographier et filmer des participant·e·s sans leur consentement est interdit. Pensez à demander avant de prendre des photos! 


Respectez les signes «No photography» ou «Pas de photo». 


<h2><span> PARENTS  </span></h2>

Préparez vos enfants: expliquez-leur à l’avance ce qu’iels pourraient voir ou entendre: nudité, art iconoclaste, langage vulgaire et/ou comportements étranges font partie intégrante de l'événement. 
Quand vous arrivez à L’OsstidBurn - faites le tour de l’événement avec les enfants et aidez-les à identifier les endroits qui pourraient les aider à se repérer. Visitez le HQ Sécurité. Nos Rangers auront des conseils pour vous. Les enfants pourront aussi s’y retrouver s’iels sont perdu·e·s. 


