# AFFAIRES À APORTER ET À NE PAS APPORTER! {-}

<h2><span>CE QUE TU DOIS APPORTER</span></h2>

**CAMPING & ÉQUIPEMENT** 

* Râteaux, gants de travail, petite hache, sécateurs pour dégager un espace pour votre campement.  
* Eau: Aucune source d’eau ne sera disponible sur  place. Nous conseillons 2L par personne et par jour.  
* Nourriture 
* Tente
* Bâches (Il pleut souvent pendant les dates de l'Osstidburn)
* Un ou plusieurs sacs de couchage, couvertures, manteaux, etc. (Prévoir assez de trucs chauds pour être confortable lors des nuits fraîches - ça prend plus qu’on pourrait penser!)  
* Cuisinière, glacière, bol, ustensiles, combustible, casserole et accessoires de cuisine… 
* Extincteur 
* Savon et liquide à vaisselle écologiques 
* Apportez votre « CUP »! Vous ne savez jamais quand un bar sera ouvert 
* Lumière: lampe frontale, lampe de poche, torche,  EL Wire pour vous ou votre tente. Évitez les  «glowsticks». Ils ne sont ni réutilisables ni écologiques. 
* Structures pour l'ombre, parasols, ombrelles, tissus; quelque chose pour vous protéger du soleil…  et de la pluie! 
* Duct tape et cordage 
* Insectifuge [Anti Moustique] 
* Crème solaire 
* Sacs-poubelle et sacs de recyclage 
* Cendrier portable pour les personnes qui fument 
* Trousse médicale 
* Chaise de camping 
* Accessoires, bannières, signalisation ou décoration qui pourrait rendre l’expérience plus agréable pour vous et pour vos voisin·e·s 
* Bouchons pour les oreilles 
* Lingettes nettoyantes 
* Désinfectant pour les mains


**VÊTEMENTS**

* Vêtements chauds et moins chauds. Préparez-vous à des journées chaudes et des nuits fraîches 
* Plusieurs paires de chaussettes, en cas de pluie et de froid 
* Imperméable, bottes de pluie 
* Costumes 


**EXTRAS**

* Instruments de musique 
* Cadeaux à donner à des nouveaux·lles ami·e·s 
* Maquillage 
* Accessoires de jonglerie 
* Votre ouverture d’esprit, votre générosité, votre sens de l’humour, et votre sourire 

<h2><span> CE QUE TU NE DOIS PAS APPORTER </span></h2>  

* Lasers
* Armes à feu 
* Articles faisant de la MOOP – plumes, confettis,  paillettes, sable, fleures séchés etc. 
* Articles suremballés – à éviter ou à jeter avant de partir 
* Feux d’artifice/Fusées 
* Accessoires en polystyrène/styrofoam 
* Animal de compagnie 
* Évitez les récipients de verre de toute sorte, si possible. Optez pour des canettes. 

