# CAMPING, GENERATRICES, SON ET AUTRES INFOS {-}

<h2><span>CAMPER À L’OSSTIDBURN </span></h2> 


Les camps thématiques auront des zones de camping clairement identifiées. Si vous ne faites pas partie d’un camp thématique, installez-vous dans une zone de libre-camping. 

Il y aura des camps sonores à L’OsstidBurn qui joueront du son amplifié au cours de la nuit. Prenez en compte au moment de vous installer. Si vous avez le sommeil léger, il est possible de s'installer plus haut, près de la plaine afin de passer des nuits plus calmes. 


Nous sommes à quelques centaines de mètres de la  frontière américaine. Évitez de vous éloigner de ce  côté. Pour votre liberté, respectez les limites du  terrain. Nous ne voulons pas vous perdre aux mains de troopers américains ;)  


La nuit, promenez-vous à deux. Il y a des ours dans le coin. Note: Les ours n’aiment pas le son amplifié, ne vous inquiétez pas trop. 

Aidez-vous les un·e·s les autres pour faire des «tick checks» régulièrement.


<h2><span> GÉNÉRATRICES </span></h2>


Soyez responsables lorsque vous utilisez des génératrices afin d’éviter de contaminer le sol et l’eau du site. Les fuites et renversements sont dangereux à la fois pour les participant·e·s et pour la forêt. Les feux d’essence sont extrêmement dangereux et difficiles à éteindre et augmentent drastiquement le risque de feux de forêt. Si vous avez des questions concernant l’usage de votre génératrice dans la forêt, veuillez contacter les Rangers ou l’équipe de FAST. 

* Toute essence pour génératrice doit être entreposée à plus de 3 mètres (10 pieds) de la génératrice, et 15 mètres (50 pieds) de tout feu de camp ou autre flamme ouverte. 
* Ne jamais installer de génératrice dans une tente utilisée pour dormir ou tout contenant scellé. 
* En cas de déversement d’essence, contactez les Rangers immédiatement. 
* Ne laissez pas votre génératrice rouler inutilement. Si vous n’avez plus besoin d’électricité, veuillez arrêter la génératrice. 
* N’éteignez pas de génératrice qui ne vous appartient  pas sauf en cas d’urgence ou de danger immédiat. Tentez plutôt de trouver son ou sa propriétaire si elle pose problème ou vous incommode. 
* Nettoyez toutes les feuilles et brindilles dans un espace de 1.5 mètres (5 pieds) autour de votre génératrice. 
* Gardez en tout temps un extincteur d’incendie en lieu visible et à moins de 5 mètres (16 pieds) de votre génératrice. 
* Les rallonges électriques enroulées peuvent chauffer et s’enflammer lorsqu’elles transportent un courant élevé. Ne les laissez pas à proximité de votre carburant ou de votre génératrice. 


<h2><span> POLITIQUE DE SON
«GANGRÈNE PAS DES AUTRES»  </span></h2>  

La politique complète de SonCoeur (Sound Core) est disponible sur le site de L’OsstidBurn: 
https://losstidburn.org/a-propos/politiques/ 

L’équipe de SonCoeur (Sound Core) croit en la capacité des opérateur·trice·s de systèmes de son à s’auto réguler et nous en appelons à leur bon jugement et leur capacité à s’adapter aux diverses situations que représente un burn. 

Il n’y aura pas de «police du son» et de patrouille pour s’assurer que les règles seront respectées. Par contre, les règles sont assez claires et précisent que n’importe quel·le participant·e est en droit de consulter un camp (et son sonomètre) afin de vérifier son niveau sonore. 

* Tous les systèmes de son de catégorie 1+  (voir le guide) doivent s’enregistrer avant  l’événement. 
* Limite en tout temps de 100 décibels à 5m (pondération dBC). 
Période de silence (sans musique amplifiée ni génératrices) entre 6 et 10 am le vendredi, samedi, dimanche et lundi (de 6h au début du GTFO). 
* Un·e opérateur·trice doit être à proximité pendant le fonctionnement de son système de son. En aucun cas un système amplifié ne devrait être laissé fonctionnel sans personne réveillée autour (il peut y avoir exception pour une installation d’art à un volume raisonnable). 
* Une situation exceptionnelle peut demander des mesures exceptionnelles.


Cette politique est sujette à changement au courant de l’événement - on cherche à établir une bonne relation avec la ville et les voisin·e·s alors soyez coopératif·ve·s si un·e membre de SonCoeur vous demande de diminuer le niveau sonore et surtout ne montez pas le volume 20 minutes plus tard. 


Après deux avertissements, vous devrez couper le son pour le reste de l’événement. 
Nous rappelons que les participant·e·s ont toujours le droit de communiquer poliment leur opinion au sujet du niveau sonore d’un soundcamp. Un sound camp à la liberté de prendre en compte ou non le commentaire, en autant que les règles de son aient été respectées. Faisons de notre mieux pour nous mettre à la place de l’autre et ne pas causer de migraine inutile (que ce soit avec du son ou des conflits). 


<h2><span> TOILETTE / PORTA POTTIES </span></h2>  

Prenez-en soin, gardez-les propres pour les suivant·e·s.  

**CE QUI VA DANS LES TOILETTES**

* Ce qui sort de votre beau body  
* Papier de toilette (1 épaisseur) 

À ne pas mettre dans les Porta-Potties: tampons, serviettes hygiéniques, essuie-mains, couches, mégots de cigarettes ou tout autre déchet. Apportez un sac avec vous pour en disposer.  

