# CAMPING & STUFF {-}

<h2><span>CAMPING AT L’OSSTIDBURN</span></h2> 


Theme camps will be given clearly marked camping areas. If you’re not affiliated with a Theme camp, please camp in an open-camping area.

There will be sound camps at L’OsstidBurn that will play amplified sound throughout the night. Please take this into account when choosing your location. If you are a light sleeper, it is possible to find quieter spots at the top (closer to the Plana).

We’re only a few hundred meters away from the American border. Don’t wander too far away. For your own personal safety and freedom, stay within the limits of the site. We don’t want to go on a mission to retrieve you from U.S. customs ;)

Don’t go out by yourself at night. There are bears in the area. Note: Bears don’t like amplified noises, so they should keep their distance.

Help each other do tick checks regularly.



<h2><span> GENERATORS </span></h2>


Please be responsible when using generators and gasoline to avoid contaminating the ground and water. Leaks and spills are dangerous for participants and the forest. Gasoline fires are extremely hazardous and difficult to put out, and drastically increase the risk of forest fires. If you have questions about using your generator safely in the forest, please contact Rangers or FAST.

* All gas for generators should be stored in the shade at least 3m (10 ft) from your generator and 15m (50 ft) from any fire pit/burn barrel/open flame.  
* Never run a generator in a sleeping tent or other enclosed space.
* In the event of a gasoline spill, contact the Rangers immediately.
* Do not let your generator run needlessly. If you don’t need power, turn it off.
* Do not turn off a generator that is not yours except in case of emergency or immediate danger. Try instead to find its owner if it poses a problem or bothers you.
* Clear all leaves and twigs from within a 1.5-meter (5 ft) area around your generator.
* Keep a fire extinguisher in a visible location within 5 meters (16 ft) of the generator at all times. 
* Coiled extension cords can heat up and even catch fire when they carry a large load. Do not leave extension cord coils close to your gasoline or generator.



<h2><span> SOUND POLICY </span></h2>

The SonCoeur (Sound Core) policy guide is available on the L’OsstidBurn website:
https://losstidburn.org/en/reports-and-policies/

The SonCoeur team believes in the sound system operators’ ability to self-regulate and we appeal to their best judgment and ability to adapt to the various situations that a burn represents.

There will be no “sound police” or patrol to enforce the rules. That being said, the rules are quite clear and specify that any participant is entitled to consult a camp (and its sound level meter) in order to check noise level.
 
 
* All category 1+ sound systems (check the guide) must register before the event.
* Limit at all times is 100 decibels at 5m (dBC weighting).
* Quiet hours (without amplified music and generators) between 6AM and noon on Thursday, Friday, Saturday, Sunday and Monday (from 6AM until GTFO).
* An operator must be nearby while their sound system is running. Under no circumstances should an amplified system be left in operation * without anyone awake around (some exceptions could be made for an art installation).
* An exceptional situation may require exceptional measures.


This policy is subject to change. We are looking to establish a good relationship with the neighbours and the Township, so please cooperate if we ask you to turn it down (and especially do not turn it back up afterwards!!!)

After two warnings, you will have to cut your sound for the rest of the event.

Remember, participants always have the right to politely express their opinion about the noise level of a soundcamp. The soundcamp is free to agree or not (if the rules are correctly followed). Let’s do our best to put ourselves in the other person’s shoes and not cause any unnecessary headaches (whether caused by sound or conflict).

<h2><span> TOILETS / PORTA-POTTIES </span></h2>  

Take care of them and keep them clean for the next person. 

**WHAT GOES IN THE TOILET**

* What comes out of your sweet body 
* Toilet paper (single-ply)


Do not put any of the following in the Porta-Potties: tampons, sanitary napkins, hand towels, diapers, cigarette butts or any other waste. Bring a bag with you to dispose of such items.
