# LNT {-}


<h2><span> LAISSE PAS D'TRACE (LNT) </span></h2> 


À L’OsstidBurn, on respecte le terrain qui nous accueille. On vient, on vit, on repart **sans laisser d’trace**. Même mieux : on essaie de **laisser l’endroit en meilleur état** encore qu’à notre arrivée.

Il n’y aura **aucun conteneur à vidange** sur place et à la sortie de l'événement.

Alors **ramène tout ce que tu apportes**, déchets inclus (oui, même le trognon de pomme).

Pense à prendre **des sacs à ordures solides**, des contenants pour tes restes, et du matos pour gérer ton bordel.

Et pitié : **pas de pipi sauvage**, surtout pas à côté de la rivière !


RESPONSABILITÉ COLLECTIVE

La propreté du site et son entretien sont l’affaire de tout le monde.
**Emporte toujours un petit sac sur toi** pour ramasser les déchets que tu croises, même s’ils sont pas à toi.
Et surtout, participe au **MOOP SWEEP de fin d’événement**, en plus de celle que vous devez faire à votre camp : c’est un moment collectif, joyeux, gratifiant (et peut-être boueux).

**LA MOOP? QUESSÉ**

MOOP est un acronyme pour ‘’Matter Out Of Place’’, un terme qui réfère à tout ce qui ne provient pas à l’origine de la terre sur laquelle l’événement a lieu. 
Mégots de cigarette, bouchons de bouteille, «glowsticks», feux d’artifice, plumes, paillettes, confettis, morceaux brisés de bois, plastique, costume, métal ou verre…
Les matières organiques, même si biodégradables, sont également de la MOOP. Si tout le monde jetait son cœur de pomme dans le bois, le site deviendrait rapidement un dépotoir et pourrait attirer des animaux. Notre impact sur l’environnement doit être le plus infime possible.
Contrairement aux festivals grand public, il n’y a aucune installation pour les déchets ou le recyclage sur le site d’un événement LNT. Tout ce qui est amené sur le site de L’OsstidBurn doit repartir avec vous, incluant vos déchets. Assurez-vous d’en disposer de façon responsable après l’événement.


<h2><span>GUIDE DES BONNES PRATIQUES LNT </span></h2>

Pendant vos préparatifs, il est impératif de consulter et de lire attentivement le guide des bonnes pratiques LNT : https://losstidburn.org/laisse-pas-dtrace/ 

Ce guide répondra à la plupart de vos questions en matière de LNT. Si toutefois vous aviez d’autres interrogations, n'hésitez pas à contacter la communauté de L'OsstidBurn via sa page Facebook afin de trouver les réponses dont vous avez besoin, ou écrivez-nous : lnt@losstidburn.org 

**MOOP SWEEP DE FIN D'ÉVÉNEMENT**

Le comité LNT veille à ce que le bois demeure en bon état, voire dans un meilleur état que lorsque nous sommes arrivé·e·s. 
Une session de nettoyage global du site aura lieu de 14h à 18h30 le mardi 24 juin. Pour vous inscrire à cette session, dirigez-vous vers la plateforme d’inscription des volontaires.
https://participation.losstidburn.org/

<h2><span>MOOP MAP</span></h2>

Une MOOP Map est créée après chaque édition de L’OsstidBurn, à partir des données récupérées lors du MOOP Sweep (photos de la MOOP ramassée). Elle permet de visualiser le niveau de propreté des différents camps, emplacements d’installations artistiques et espaces communs, tels qu’ils ont été laissés à la fin de l’événement, avant le MOOP Sweep.

Ces données sont ensuite étudiées par le comité LNT, puis utilisées lors de la préparation des éditions futures afin d’octroyer les placements aux camps ou artistes.

**La plaine, les sites de parking, le chemin, le bois et la rivière sont des espaces communs. Il est de votre responsabilité en tant que participant.e de veiller à la propreté de ces espaces, au même titre que votre campement.**
