# SECURITY {-}

We are Burners, we care for our community. We mediate, offer conflict resolution assistance, and act in emergencies. 

If you need help, you can find us at Safety HQ. You can find the location on the map.

<h2><span>Rangers</span></h2> 

Rangers are volunteer sober participants that are here to help you in case of problems or emergencies. You can usually spot them wearing a forest green shirt and/or a green light. They patrol in groups of two and are equipped with radios so they can communicate more quickly with other teams if needed. The First Aid volunteers are on call and can be reached by radio, especially via the Rangers. If you feel caught in an uncomfortable situation, the Rangers and First Aid will be there to support you. Sanctuary volunteers can also accommodate you and provide you with a more secure, well-lit and weatherproof space.

<h2><span>Sanctuary</span></h2> 

The Sanctuary is a safe(r) space for participants who are going through a difficult experience and find themselves in need of support or a time-out. Volunteers will be on site to chat, keep company and generally offer a comforting presence. The sanctuary is meant to be a place to relax and ground yourself; it is cozy, well lit, warm and dry, with snacks and tea available. Harm reduction tools and supplies (such as condoms, dental dams, gloves, etc...), as well as information on drug use and safer sex, will be readily available at all times. The sanctuary offers activities, discussions and workshops on consent, cultural appropriation and safer drug use.

<h2><span>And...</span></h2> 

Please exercise caution. Take care of your friends and yourself. Remember to drink water and to eat. And have fun!
We have medical supplies at Safety HQ. Come see us if you don’t have what you need in your own first aid kit.

At night, make sure you can see and be seen. Always  carry at least one flashlight or headlamp.

-- The L’OsstidBurn Safety Team

