# LAST INFORMATION {-}

<h2><span>LOST & FOUNDS</span></h2>

This year, the Lost & Found station will be located at **Safety HQ**. Head there to drop off found items or reclaim your precious belongings.

<h2><span>EXODUS</span></h2>

Tuesday, June 24 : 5:00 AM to 2:00 PM

PACK OUT WHAT YOU PACK IN!!


Take everything you brought with you! Pick up all trash. Take a moment to check your campsite and any other area you visited before leaving.

By 2:00 PM, all participants (except LNT volunteers) must have left the site.

Just like during arrival, only 4x4 vehicles with a 12-inch (30 cm) clearance may be allowed on the trail if terrain conditions permit.
Due to heavy traffic on the trail during Exodus, a timed schedule will be set up for vehicles entering and exiting the trail.
Please check that schedule to plan your departure.

**The Leave No Trace Sweep** will take place from 2:00 PM to 6:30 PM:

* Line up side by side!
* Leave one meter of space between each person.
* Walk forward and pick up everything you see!


**MOOP OUT!**

<h2><span> THE END </span></h2>

Thank you for reading this guide.

The more it’s read, the better everyone’s experience will be at L’OsstidBurn.

--- 

We are all responsible for what this event is going to be! We do not know what will happen at OsstidBurn – that’s the beauty of the event and the community that creates it.
