# DERNIÈRES INFOS {-}

<h2><span>OBJETS TROUVÉS</span></h2>

Cette année, la station de Lost & Found se situera ‘’HQ Sécurité’’. Adressez-vous aux équipes présentes sur place afin d’y déposer tout objet trouvé ou retrouver “votre précieux”. 


<h2><span>EXODUS</span></h2>

Repartez avec tout ce que vous avez apporté! 


Mardi 24 juin à 14h00 : tous·es les participant·e·s  (à l’exception des volontaires du Leave No Trace) doivent avoir quitté les lieux. Compte tenu du fort volume de trafic sur le sentier lors de l’exode, un horaire sera établi pour les véhicules avec des plages pour entrer et sortir du sentier. Veuillez le consulter pour planifier votre départ. La session de Leave No Trace aura lieu de 14h à 18h30. 


Prenez le temps de vérifier votre emplacement et les lieux que vous avez fréquentés avant de quitter.  


Tout déchet doit être ramassé. 


Mettez-vous tous.tes en ligne! 


Laissez un mètre d’espace entre vous. 


Avancez et ramassez tout ce que vous voyez! MOOP OUT!

**MOOP OUT!**

<h2><span> FIN. </span></h2>

Merci d’avoir lu ce guide. 
Plus il sera lu, meilleure sera l’expérience pour  tout le monde à L’OsstidBurn.

--- 

Nous sommes tous·tes responsables de ce que sera cet événement! Nous ne savons pas ce qui se passera à L’OsstidBurn, c’est la beauté de l’événement et de sa communauté! 
